#include <mbp/examples/bimodal.hpp>
#include <mbp/examples/two_level.hpp>
#include <mbp/examples/gshare.hpp>
#include <mbp/examples/tournament.hpp>
#include <mbp/examples/2bcgskew.hpp>
#include <mbp/examples/hashed_perceptron.hpp>
#include <mbp/examples/tage.hpp>
#include <mbp/examples/batage.hpp>
#include <mbp/examples/tage_sc_l_cbp5.hpp>
